### ISSUE TITLE
[Suggestion] Language in which Untranslated words are Displayed

### ISSUE THREAD

**Issue by YuevUwU** [TeamFlos/phira#226]
### Now
In the following languages, untranslated words will be displayed as `zh-TW`. _Is this expected?_ 
(v0.0.9 it displayed as `zh-CN`. I think this is determined by the last language on l10n array.)
- Bahasa Indonesia
- 日本語
- Polski
- แบบไทย

### Suggestion
I think it would be more **international** to display it in **English**.

**Comment by Mivik** [comment]
The current semantic is, the user-selected language is of the top priority, and if a translation does not present in that language, the system default language (determined by your system settings) is used, and then goes en-US.

So in the above situation, the reason can be that the author's system default language is zh-TW instead of en-US. If you think this semantic is unjustified, reopen the issue with your reasons.
